# Generated by Django 4.2.27 on 2026-01-02 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('socio', 'Socio'), ('empresa', 'Empresa')], max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('identity_number', models.CharField(blank=True, help_text='Cédula de identidad', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('rut', models.CharField(blank=True, help_text='RUT de la empresa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
