# Generated by Django 4.2.27 on 2026-01-05 12:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador único para la URL (ej: 'faq', 'sobre-nosotros')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Título de la página que se mostrará en la interfaz', max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Contenido de la página con editor visual WYSIWYG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Estática',
                'verbose_name_plural': 'Páginas Estáticas',
                'ordering': ['title'],
            },
        ),
    ]
