# Generated by Django 4.2.27 on 2026-01-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staticpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Página Estática', 'verbose_name_plural': 'Páginas Estáticas'},
        ),
        migrations.AddField(
            model_name='staticpage',
            name='category',
            field=models.CharField(choices=[('informacion', 'Información'), ('politicas', 'Políticas'), ('recursos', 'Recursos'), ('otros', 'Otros')], default='informacion', help_text='Categoría para el menú', max_length=20),
        ),
    ]
