# Generated by Django 4.2.27 on 2026-01-08 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_staticpage_options_staticpage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado_pago_subscription_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('preapproval_id', models.CharField(blank=True, help_text='ID de preaprobación en MP', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Esperando primer pago'), ('active', 'Activa'), ('paused', 'Pausada (fallo de pago)'), ('cancelled', 'Cancelada'), ('failed', 'Fallo permanente')], db_index=True, default='pending', max_length=20)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_payment_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('mercado_pago_updated_at', models.DateTimeField(blank=True, help_text='Última vez que sincronizamos con MP', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subscription_active',
            field=models.BooleanField(db_index=True, default=False, help_text='True si tiene cupón o suscripción activa en MP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('no_subscription', 'Sin suscripción'), ('active', 'Activa'), ('inactive', 'Inactiva'), ('cancelled', 'Cancelada')], default='no_subscription', help_text='Estado sincronizado de la suscripción', max_length=20),
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único del cupón', max_length=100, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Fecha de expiración del cupón')),
                ('months_of_validity', models.IntegerField(default=3, help_text='Meses de validez desde la creación (informativo)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que lo utilizó (null si no fue usado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Ej: subscription_updated, payment.updated', max_length=100)),
                ('mercado_pago_event_id', models.CharField(db_index=True, help_text='ID único del evento en MP', max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló el procesamiento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'created_at'], name='main_subscr_subscri_c4718a_idx'), models.Index(fields=['processed'], name='main_subscr_process_d5eea2_idx'), models.Index(fields=['event_type'], name='main_subscr_event_t_b88519_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='main_subscr_user_id_e08e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['mercado_pago_subscription_id'], name='main_subscr_mercado_26d0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_payment_date'], name='main_subscr_next_pa_32e413_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['code', 'is_used'], name='main_coupon_code_68cad6_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['expires_at'], name='main_coupon_expires_afe9b5_idx'),
        ),
    ]
